name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          always-auth: true
          scope: "@cultural-map"
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Create .npmrc
        uses: ferluisxd/create-npmrc@3
        with:
          org_name: cultural-map
        env:
          AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Create .env file
        uses: DeveloperRic/action-create-env@v1.0.4
        with:
          full_text: |
            API_URL=${{ secrets.PROD_API_URL }}

      - name: Override "prepare" script
        run: pnpm pkg delete scripts.prepare

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check lint
        run: pnpm lint:check

      - name: Check types
        run: pnpm type:check

      - name: Run build
        run: pnpm build

      - name: Install Netlify
        run: pnpm add -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod
