name: Developer

on:
  push:
    branches-ignore:
      - main

jobs:
  health-check:
    name: Health check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Yarn
        run: npm install -g yarn

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          always-auth: true
          scope: "@ficbr"
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      - name: Create .npmrc
        uses: 1arp/create-a-file-action@0.4.5
        with:
          file: ".npmrc"
          content: |
            engine-strict=true

            @ficbr:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}

      - name: Create .env file
        uses: DeveloperRic/action-create-env@v1.0.4
        with:
          full_text: |
            API_URL=${{ secrets.DEV_API_URL }}

      - name: Override "prepare" script
        run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: yarn install

      - name: Check lint
        run: yarn lint:check

      - name: Check types
        run: yarn type:check

      - name: Run build
        run: yarn build
